# Generated by Django 3.1.6 on 2021-03-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210302_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_secondary',
            field=models.ImageField(blank=True, upload_to='category'),
        ),
    ]
