# Generated by Django 3.1.6 on 2021-03-30 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField()),
                ('image', models.ImageField(upload_to='gallery')),
                ('total_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('votes_this_month', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voted_by', models.ManyToManyField(blank=True, related_name='voter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Picture',
                'verbose_name_plural': 'Gallery Pictures',
            },
        ),
        migrations.CreateModel(
            name='PictureOfTheMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('picture_of_month', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.picture')),
            ],
            options={
                'verbose_name': 'Picture of the month gallery',
                'verbose_name_plural': 'Pictures of the month gallery',
            },
        ),
    ]
