# Generated by Django 3.1.6 on 2021-03-20 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskypicture',
            name='total_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userskypicture',
            name='votes_this_month',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateField(auto_now_add=True)),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voted_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='gallery.userskypicture')),
            ],
        ),
        migrations.CreateModel(
            name='PictureOfTheMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_of_the_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic_of_month', to='gallery.userskypicture')),
            ],
        ),
    ]
