# Generated by Django 3.1.6 on 2021-04-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pictureofthemonth',
            name='picture_of_month',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picoftm', to='gallery.picture'),
        ),
    ]
