# Generated by Django 3.1.6 on 2021-03-20 07:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0002_auto_20210320_0357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSkyPicture',
            new_name='Picture',
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Gallery Picture', 'verbose_name_plural': 'Gallery Pictures'},
        ),
        migrations.AlterModelOptions(
            name='votes',
            options={'verbose_name': 'Votes', 'verbose_name_plural': 'Votes'},
        ),
    ]
