# Generated by Django 3.1.6 on 2021-03-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210320_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='total_votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='votes_this_month',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
