# Generated by Django 3.1.6 on 2021-03-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210320_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='total_votes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='votes_this_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
