# Generated by Django 3.1.6 on 2021-03-24 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0007_auto_20210324_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='voted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
